### ISSUE TITLE
How to split up large controllers/views?

### ISSUE THREAD

**Issue by DieterAtWork** [johnpapa/angularjs-styleguide#214]
Hi, We have a fairly large application and had split up our controllers/views to change context and reuse them. So in our main template we would do the following to include a sub-view (like when having tabs which can have different types of controllers/views:

```html
<ng-include
	src="'/js/subtopic/template/SubTopicTemplateInfo.html'"
    data-ng-controller="SubTopicTemplateInfoController"
	data-ng-model="subTopicTemplate.generalInfo">
</ng-include>
```

Then in the controller for that piece, we would get the actual data (context) that's need to be used by that controller like this (REMARK: I already have tranformed the controller to this styleguide):

```javascript
SubTopicTemplateInfoController($scope, $attrs) {
	// $scope only used for $eval attributes!
	var vm = this;
	vm.info = $scope.$eval($attrs.ngModel); // How to do this now without $scope ???
},
```

This way, we can use the controller/view in other places of our app, and have it all more clear what context the controller is working on. I just can't see how we could get the data (context) in our controller without using $scope. I also don't find a similar situation in the demo application or in the styleguide. Can you please comment how this can be done? Or maybe another way of doing this?

**Comment by DieterAtWork** [comment]
I know this can be avoided if the back-end is also correctly modularized, as then you can give up an id which the controller can use to ask a service for the model. But this isn't always the case...

**Comment by johnpapa** [comment]
Not sure I follow. The ng-include has html/view. Why not put the controller inside the view that uses it?

It looks like you want to have the view use the content from the outer controller. That can work. But have you looked into isolating the views using ui-router and its states? That may wrk better.

BTW - probably a better place to ask this is StackerOverflow.

**Comment by wardbell** [comment]
If I understand correctly, you're trying to communicate data from one controller to another; in this case you want to pass `generalInfo` to the inner "sub-controller",  `SubTopicTemplateInfoController`. I will proceed with that intent in mind.

The easiest solution is to not have the sub-controller at all. When you ngInclude the template with no controller specification, the template is bound to the outer controller and you're in good shape. But we'll assume you have good reasons for a separate controller.

You could specify that controller inside the template as John suggested. That is just fine even if the sub-controller is re-usable in other templates! Of course it doesn't work if the template can be bound to multiple controllers ... a circumstance I strive to avoid ... almost always successfully.

However, that doesn't solve the problem of conveying information from the outer controller to the sub-controller. 

It is safe to say that the "controllerAs" syntax impedes your ability to access external context ... specifically context up the $scope inheritance chain. This is not a failing; it is by design!  One of the principle complaints about $scope is that it is a pseudo-global with unfettered access (and potential manipulation) across controller boundaries. That's one reason (not the only reason) that $scope is going away in version 2.  It's a reason we should be reluctant ... ***as a matter of style*** ... to appear to promote this form of cross-controller sharing.

I personally favor the use of a "controller state" service for this kind of thing. That's the generally accepted solution for preserving state across controller lifetimes. It works just as well here.

But if you don't like that and you're comfortable with "dirty", well ... there is always `$scope`. You've taken a rather round about way of doing it with `$eval` and all. Why pretend? You might as well just inject `$scope` and walk up the chain to get what you want (e.g., `$scope.$parent.vm.generalInfo`). Isn't that awful? It sure is. But I'd argue it's dirtier than calling $eval over text-based attributes. It's up to you. 

IMO, neither of the dirty approaches belong in a style guide. If the guide tackles this problem at all, perhaps it should discuss the "controller-state" service gambit.

Cheers!
