### ISSUE TITLE
Include ES6 styles

### ISSUE THREAD

**Issue by dbabaioff** [johnpapa/angularjs-styleguide#259]
It would be nice to include ES6 in the style guide. Like, how to write the different pieces (controllers, factories/services/providers, directives...) using ES6.

**Comment by johnpapa** [comment]
Interesting idea, but its a big shift and would muddy the waters.

**Comment by aciccarello** [comment]
This sounds like it should be a fork to me. I'd love to see it though.

**Comment by markevich** [comment]
@aciccarello it's better to investigate angular 2.0 with es6 and web components. :fork_and_knife::fork_and_knife:

**Comment by voor** [comment]
@markevich Would probably make more sense to use TypeScript than ES6 at this stage in Angular 2.0.

**Comment by aciccarello** [comment]
@markevich 
True but I'm trying to learn ES6/TypeScript now in order to make migration to Angular 2 simpler. Classes are the most significant change and it will help encapsulate business logic into something migrateable. 

@voor
I agree, though there still are some ES6 features missing/syntax differences in the current stable TS 1.4  version I'm using that will likely change as TypeScript progresses. I imagine best practices will tend toward the more standard ES6 syntaxes.

**Comment by johnpapa** [comment]
Using a function or a class is not very different in JavaScript. If you keep it one level its really no better or worse. And I do think its important not to go nuts with OOP and inheritance in JavaScript.

Certainly learn TS and ES6. It can only help you moving forward. But be careful not to overuse classes.

**Comment by rwwagner90** [comment]
I forked the style guide and converted it all to ES6/ES2015. Please check it out and feel free to submit PRs and contribute! https://github.com/rwwagner90/angular-styleguide-es6
