### ISSUE TITLE
IIFE on build with gulp or grunt

### ISSUE THREAD

**Issue by blackjid** [johnpapa/angularjs-styleguide#262]
What do you think about wrapping your files content in a IIFE on the build process instead of the file themself??? 

Could be done with [gulp-wrap](https://www.npmjs.com/package/gulp-wrap/) adding something like this to your gulpfile

```js
gulp.src("./src/*.js")
    .pipe(wrap('(function(){\n"use strict";\n<%= contents %>\n})();'))
    .pipe(gulp.dest("./dist"));
```

**Comment by wardbell** [comment]
I assume the point is that you're guarding against the possibility that something leaks into the global namespace because one of the source files is not itself an IIFE and does not "use strict".

That's belt-and-suspenders thinking. It seems harmless, but might not be. Your imposing "use strict" over the entire concatenated contents. You'll break the code if someone (why? they might have reasons) needs a code block to execute in non-strict mode. Whether you like that or not, I've seen this cause bugs.

Personally, I think it is overkill + the non-strict risk and I wouldn't do it. I wonder what others think.

**Comment by johnpapa** [comment]
I prefer to use IIFE in my code explicitly. This allows me to choose when to use it and I can opt out on a file basis if I need to. Plus even when I do it for all files, I don;t need to process my files to run them. I like to do as little as possible to my files before running them in dev mode (unlike when I do a full optimize/build). Touching every file and updating them can be slow too (see ng-templates).

It's a good question, but I personally do not feel its worth it.
