### ISSUE TITLE
LIFT Angular and TypeScript

### ISSUE THREAD

**Issue by rcollette** [johnpapa/angularjs-styleguide#290]
I am going through your Pluralsight course and attempted to move controller declarations like `angular.module("app").controller("PurchaseOrdersController", PurchaseOrdersController);` above the TypeScript class declaration for the controller.  That results in an error

```
Error: error:areq
Bad Argument
Argument 'PurchaseOrdersController' is not
```
(The fact that the stacktrace is lost and, the error message is incomplete and offers no description of what happened, is a separate issue)

This is because typescript generated classes are defined as an IIFE assigned to a var.  At the time that the `controller(...)` function is called, the variable holding the reference to the class is not yet defined.

So where you can place `controller()` depends on whether you are declaring the controller like:
`function MyController(){}` 
or
`var MyController = (function(){
function MyController(){}
return MyController;}());`

I am not sure this is so much an issue with the style guide as it is a caveat.

A bad error message combined with a false presumption that such ordering works in all cases can lead to some wasted debugging time.

**Comment by johnpapa** [comment]
There is a big difference (as you found out) between these: `function foo() { }` and `var foo = function() {};`

That's why I use the former in my style guide and reference in in a few blog posts on why I do this. 

Typescript generates code from TS which is why you see what you see there. When using TS or CS or AS with this style guide I am certain there are differences you must take into account because they do things differently than plain old vanilla JavaScript.
